<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/runtime.php'; require_once __DIR__ . '/../includes/actions.php'; require_once __DIR__ . '/../includes/print_pricing.php'; require_auth();
$id=(int)($_GET['id']??0); if($id<1) die('Solicitud inválida.');
$st=$pdo->prepare('SELECT r.*,c.name customer_db_name,c.email customer_db_email,c.phone customer_db_phone FROM cp_web_quote_requests r LEFT JOIN cp_customers c ON c.id=r.customer_id WHERE r.id=?');$st->execute([$id]);$r=$st->fetch(PDO::FETCH_ASSOC);if(!$r)die('Solicitud no encontrada.');
$st=$pdo->prepare('SELECT * FROM cp_web_quote_files WHERE request_id=? ORDER BY id');$st->execute([$id]);$files=$st->fetchAll(PDO::FETCH_ASSOC);
$st=$pdo->prepare('SELECT i.*,f.original_name FROM cp_print_request_items i LEFT JOIN cp_web_quote_files f ON f.id=i.file_id WHERE i.request_id=? ORDER BY i.id');$st->execute([$id]);$items=$st->fetchAll(PDO::FETCH_ASSOC);
$total=array_sum(array_map(fn($x)=>(float)$x['subtotal'],$items)); $title='Solicitud CPQ-'.$id;
require __DIR__.'/../includes/header.php';?><link rel="stylesheet" href="/assets/css/print-reception.css?v=20260926-1"><div class="pr-toolbar"><div><span class="pr-eyebrow">SOLICITUD #CPQ-<?=str_pad((string)$id,6,'0',STR_PAD_LEFT)?></span><h2><?=e($r['customer_db_name']?:$r['customer_name'])?></h2><p><?=e($r['phone']??'')?> · <?=e($r['email']??'')?></p></div><a class="pr-btn secondary" href="/admin/recepcion_impresiones.php">← Recepción</a></div><div class="pr-detail-grid"><section class="pr-card"><h3>Archivos y configuración</h3><?php foreach($files as $f):?><div class="pr-file"><div><strong>📄 <?=e($f['original_name'])?></strong><small><?=e($f['mime_type'])?> · <?=number_format(((int)$f['size_bytes'])/1048576,2)?> MB</small></div><a class="pr-btn small secondary" href="<?=e($f['stored_path'])?>" target="_blank" rel="noopener">Abrir</a><?php $its=array_values(array_filter($items,fn($x)=>(int)($x['file_id']??0)===(int)$f['id'])); if($its):?><div class="pr-file-spec"><?php foreach($its as $it):?><span><?=e($it['size_name']?:'Personalizado')?></span><span><?=e($it['material_name']?:'Material no indicado')?></span><span><?=e($it['color_mode']==='bw'?'B/N':'Color')?></span><span><?=e((string)$it['copies'])?> copias</span><span>$<?=number_format((float)$it['subtotal'],2)?></span><?php endforeach;?></div><?php endif;?></div><?php endforeach;?></section><aside class="pr-card pr-total"><span>Precio estimado</span><strong>$<?=number_format($total,2)?></strong><small>El precio queda registrado con la solicitud. Una cotización formal puede ajustar conceptos que requieran revisión.</small></aside></div><?php require __DIR__.'/../includes/footer.php'; ?>
