<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
$db=cp_db(); $id=(int)($_GET['id']??0);
$st=$db->prepare("SELECT * FROM cp_print_requests WHERE id=?");$st->execute([$id]);$r=$st->fetch();
if(!$r) exit('Solicitud no encontrada.');
$st=$db->prepare("SELECT i.*,s.name size_name,m.name material_name,f.name finish_name,w.original_name,w.stored_path,w.mime_type,w.size_bytes FROM cp_print_request_items i LEFT JOIN cp_print_sizes s ON s.id=i.size_id LEFT JOIN cp_print_materials m ON m.id=i.material_id LEFT JOIN cp_print_finishes f ON f.id=i.finish_id LEFT JOIN cp_web_quote_files w ON w.id=i.file_id WHERE i.request_id=? ORDER BY i.id");$st->execute([$id]);$items=$st->fetchAll();
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solicitud #<?=$id?> · Colibrí Print</title><link rel="stylesheet" href="../assets/css/colibri-print.css"></head>
<body><div class="cp-wrap"><div class="cp-brand">COLIBRÍ PRINT · PRODUCCIÓN</div><div class="cp-hero"><div><h1>Solicitud #<?=$id?></h1><p><?= cp_e($r['customer_name']) ?> · <?= cp_e($r['customer_email']) ?> · <?= cp_e($r['customer_phone']) ?></p></div><a class="cp-btn cp-btn-soft" href="recepcion_impresiones.php">← Volver</a></div>
<?php if(isset($_GET['ok'])): ?><section class="cp-card" style="border-left:4px solid #18a558"><strong>✓ <?= $_GET['ok']==='completed'?'Impresión marcada como realizada.':($_GET['ok']==='archived'?'Trabajo archivado correctamente.':'Operación realizada.') ?></strong></section><?php endif; ?>
<?php if(isset($_GET['error'])): ?><section class="cp-card" style="border-left:4px solid #c62828"><strong>⚠ <?=cp_e($_GET['error'])?></strong></section><?php endif; ?>
<section class="cp-card"><div class="cp-total-line" style="border:0;margin:0;padding:0 0 14px"><span>Total estimado</span><strong><?=cp_money($r['total_estimate'])?></strong></div>
<div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px"><strong>Estado: <?=cp_e($r['status'])?></strong><?php if(($r['archive_status']??'active')==='archived'): ?><span>📁 Archivado <?=cp_e($r['archived_at']??'')?></span><?php endif; ?></div>
<?php if(!in_array($r['status'],['completed','cancelled'],true) && ($r['archive_status']??'active')!=='archived'): ?><form method="post" action="print_request_action.php" style="display:inline-block;margin:0 8px 14px 0"><input type="hidden" name="csrf" value="<?=cp_e(cp_csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="complete"><button class="cp-btn cp-btn-primary" type="submit">🖨️ Marcar impresión realizada</button></form><?php endif; ?>
<?php if($r['status']==='completed' && ($r['archive_status']??'active')!=='archived'): ?><form method="post" action="print_request_action.php" style="display:inline-block;margin:0 8px 14px 0" onsubmit="return confirm('¿Conservar los archivos y el registro en el historial?')"><input type="hidden" name="csrf" value="<?=cp_e(cp_csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="archive"><button class="cp-btn cp-btn-soft" type="submit">📁 Conservar archivo + registro</button></form><form method="post" action="print_request_action.php" style="display:inline-block;margin:0 8px 14px 0" onsubmit="return confirm('Esta acción eliminará el trabajo y sus archivos. ¿Continuar?')"><input type="hidden" name="csrf" value="<?=cp_e(cp_csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="delete"><button class="cp-btn cp-btn-danger" type="submit">🗑️ Eliminar trabajo</button></form><?php endif; ?>
<table class="cp-admin-table"><tr><th>Archivo</th><th>Páginas</th><th>Configuración</th><th>Cobro</th></tr>
<?php foreach($items as $i): ?><tr><td><strong><?=cp_e($i['original_name'] ?: 'Archivo')?></strong><br><span class="cp-muted"><?=cp_e($i['stored_path'] ?: '')?></span><?php if(!empty($i['stored_path'])): ?><br><a class="cp-btn cp-btn-soft" href="<?=cp_e($i['stored_path'])?>" target="_blank" rel="noopener">Abrir archivo</a><?php endif; ?></td><td><?= (int)$i['page_count'] ?> pág.<br><?= (int)$i['sheet_count'] ?> hojas</td><td><?=cp_e($i['size_name'] ?: $i['size_id'] ?: '—')?> · <?=cp_e($i['material_name'] ?: '—')?> · <?=cp_e($i['finish_name'] ?: '—')?><br><?=($i['color_mode']==='color'?'Color':'B/N')?> · <?=cp_e((string)$i['copies'])?> copia(s)</td><td><?=cp_money($i['subtotal'])?><br><span class="cp-muted"><?=cp_money($i['unit_price'])?> / unidad</span></td></tr><?php endforeach; ?></table></section></div></body></html>
