-- FASE 10B / CFDI: expediente de comprobantes ya timbrados
-- Ejecutar una sola vez sobre colibrip_abcsistema.
CREATE TABLE IF NOT EXISTS cp_invoice_documents (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_id int(10) UNSIGNED NOT NULL,
  order_id int(10) UNSIGNED NOT NULL,
  uuid varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  version varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '4.0',
  serie varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  folio varchar(60) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  issued_at datetime DEFAULT NULL,
  moneda varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  emisor_rfc varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  emisor_nombre varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  receptor_rfc varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  receptor_nombre varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  subtotal decimal(15,2) NOT NULL DEFAULT '0.00',
  tax decimal(15,2) NOT NULL DEFAULT '0.00',
  total decimal(15,2) NOT NULL DEFAULT '0.00',
  forma_pago varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  metodo_pago varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  certificado_sat varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  no_certificado_sat varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  sello_cfdi longtext COLLATE utf8mb4_unicode_ci,
  sello_sat longtext COLLATE utf8mb4_unicode_ci,
  xml_path varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  pdf_path varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  xml_sha256 char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  created_by int(10) UNSIGNED DEFAULT NULL,
  created_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cp_invoice_documents_uuid (uuid),
  KEY idx_cp_invoice_documents_invoice (invoice_id),
  KEY idx_cp_invoice_documents_order (order_id),
  KEY idx_cp_invoice_documents_date (issued_at),
  KEY idx_cp_invoice_documents_sha (xml_sha256),
  CONSTRAINT fk_cp_invoice_documents_invoice FOREIGN KEY (invoice_id) REFERENCES cp_invoices(id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_invoice_documents_order FOREIGN KEY (order_id) REFERENCES cp_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cp_invoice_items (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  document_id int(10) UNSIGNED NOT NULL,
  clave_prod_serv varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  no_identificacion varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  cantidad decimal(15,6) NOT NULL DEFAULT '0.000000',
  clave_unidad varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  unidad varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  descripcion varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  valor_unitario decimal(15,6) NOT NULL DEFAULT '0.000000',
  importe decimal(15,2) NOT NULL DEFAULT '0.00',
  objeto_imp varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  created_at datetime NOT NULL,
  PRIMARY KEY (id),
  KEY idx_cp_invoice_items_document (document_id),
  CONSTRAINT fk_cp_invoice_items_document FOREIGN KEY (document_id) REFERENCES cp_invoice_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
